CREATE TABLE IF NOT EXISTS `canary_rule` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `rule_id` varchar(64) NOT NULL COMMENT '规则ID',
  `rule_name` varchar(128) NOT NULL COMMENT '规则名称',
  `route_id` varchar(64) DEFAULT NULL COMMENT '关联路由ID',
  `canary_weight` int(11) DEFAULT '10' COMMENT '金丝雀权重',
  `canary_version` varchar(32) DEFAULT 'v2' COMMENT '金丝雀版本',
  `stable_version` varchar(32) DEFAULT 'v1' COMMENT '稳定版本',
  `match_type` varchar(32) DEFAULT 'weight' COMMENT '匹配类型',
  `match_config` text COMMENT '匹配配置JSON',
  `header_name` varchar(64) DEFAULT NULL COMMENT 'Header名称',
  `header_value` varchar(256) DEFAULT NULL COMMENT 'Header值',
  `cookie_name` varchar(64) DEFAULT NULL COMMENT 'Cookie名称',
  `query_param` varchar(64) DEFAULT NULL COMMENT 'Query参数名',
  `enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_id` (`rule_id`),
  KEY `idx_route_id` (`route_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='灰度规则表';
