-- 服务信息表
CREATE TABLE IF NOT EXISTS `service_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `service_name` varchar(128) NOT NULL COMMENT '服务名（Nacos服务名）',
  `namespace_id` varchar(64) DEFAULT 'public' COMMENT '命名空间ID',
  `group_name` varchar(128) DEFAULT 'DEFAULT_GROUP' COMMENT '分组名',
  `display_name` varchar(256) DEFAULT NULL COMMENT '显示名称',
  `description` varchar(512) DEFAULT NULL COMMENT '服务描述',
  `protocol` varchar(16) DEFAULT 'http' COMMENT '服务协议：http/https/grpc',
  `base_path` varchar(128) DEFAULT NULL COMMENT '基础路径（如 /api）',
  `swagger_url` varchar(512) DEFAULT NULL COMMENT 'Swagger文档地址',
  `instance_count` int(11) DEFAULT '0' COMMENT '实例数量',
  `healthy_instance_count` int(11) DEFAULT '0' COMMENT '健康实例数',
  `status` tinyint(1) DEFAULT '1' COMMENT '服务状态：0-离线 1-在线 2-部分离线',
  `synced_from_nacos` tinyint(1) DEFAULT '0' COMMENT '是否从Nacos同步',
  `last_sync_time` datetime DEFAULT NULL COMMENT '最后同步时间',
  `metadata` text COMMENT '元数据（JSON）',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_name` (`service_name`),
  KEY `idx_namespace` (`namespace_id`),
  KEY `idx_group` (`group_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务信息表';

-- 服务实例表
CREATE TABLE IF NOT EXISTS `service_instance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `service_id` bigint(20) NOT NULL COMMENT '关联服务ID',
  `service_name` varchar(128) NOT NULL COMMENT '服务名',
  `instance_id` varchar(256) NOT NULL COMMENT '实例ID（Nacos实例唯一标识）',
  `ip` varchar(64) NOT NULL COMMENT 'IP地址',
  `port` int(11) NOT NULL COMMENT '端口',
  `weight` double DEFAULT '1.0' COMMENT '权重',
  `healthy` tinyint(1) DEFAULT '1' COMMENT '是否健康',
  `enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `ephemeral` tinyint(1) DEFAULT '1' COMMENT '是否临时实例',
  `cluster_name` varchar(128) DEFAULT NULL COMMENT '集群名',
  `metadata` text COMMENT '实例元数据（JSON）',
  `last_beat_time` datetime DEFAULT NULL COMMENT '最后心跳时间',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_id` (`instance_id`),
  KEY `idx_service_id` (`service_id`),
  KEY `idx_service_name` (`service_name`),
  KEY `idx_healthy` (`healthy`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务实例表';
